name: Deploy Next.js to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo "Deploy started..."
            cd ~/kianblog
            git fetch --all
            git reset --hard origin/main
            npm ci
            npm run build
            pm2 stop kianblog || true
            pm2 reload ecosystem.config.js --only kianblog
            pm2 save
            echo "Deploy finished!"
